---
# tasks file for mablanco.osint

- name: Install 'The Harvester'
  include: the_harvester.yml
  when: the_harvester | bool

- name: Install 'GasMasK'
  include: gasmask.yml
  when: gasmask | bool

- name: Install 'DataSploit'
  include: datasploit.yml
  when: datasploit | bool
